dat <- read.table ("f.txt", dec = ",")
sc.dat <- scale(dat)
cl <- kmeans(sc.dat, 2)
table(cl$cluster)
sapply(1:2, function(i) cl$centers[, i] * sd(dat[, i]) + mean(dat[, i]))
plot(dat, col = c("blue", "green")[cl$cluster])
legend("bottomleft", legend = c("1", "2"), fill = c("blue", "green"))
plot(dat, pch = (1:2)[cl$cluster])
legend("bottomleft", legend = c("1", "2"), pch = 1:2)
cl <- kmeans(sc.dat, 3)
table(cl$cluster)
sapply(1:2, function(i) cl$centers[, i] * sd(dat[, i]) + mean(dat[, i]))
plot(dat, col = c("blue", "green", "red")[cl$cluster])
legend("bottomleft", legend = c("1", "2", "3"), fill = c("blue", "green", "red"))
plot(dat, pch = (1:3)[cl$cluster])
legend("bottomleft", legend = c("1", "2", "3"), pch = 1:3)